services:
  hivemq-broker:
    image: hivemq/hivemq-ce
    ports:
      - "8883:1883"
      - "8884:8000"
    networks:
      - my-network
    restart: always

networks:
  my-network:

# docker compose -f dev.yaml up -d
# docker compose -f dev.yaml down -v