version: "3.8"

networks:
  my-network:

services:
  mvp-api:
    build:
      context: ./mvp/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network
    restart: always

  mvp-client:
    build:
      context: ./mvp/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - my-network
    restart: always