services:
  mvp-api:
    build:
      context: ./mvp/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network
    restart: always
    volumes:
      - ./mvp/data:/code/mvp/data

  mvp-client:
    build:
      context: ./mvp/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - my-network
    restart: always

#  hivemq-broker:
#    image: hivemq/hivemq-ce
#    ports:
#      - "8883:1883"
#      - "8884:8000"
#    networks:
#      - my-network
#    restart: always

networks:
  my-network:
