services:
  mvp-api:
    build:
      context: ./mvp/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mvp-with-broker
    restart: always
    volumes:
      - ./mvp/data:/code/mvp/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DEV_MQTT_HOST: "host.docker.internal"
      DEV_FE_MQTT_HOST: "165.227.107.127"

  mvp-client:
    build:
      context: ./mvp/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - mvp-with-broker
    restart: always

  hivemq-broker:
    image: hivemq/hivemq-ce
    ports:
      - "8883:1883"
      - "8884:8000"
    networks:
      - mvp-with-broker
    restart: always

networks:
  mvp-with-broker:
