services:
  mvp-api:
    build:
      context: ./mvp/server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - pdm-game-mvp
    restart: always
    volumes:
      - ./mvp/data:/code/mvp/data

  mvp-client:
    build:
      context: ./mvp/client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - pdm-game-mvp
    restart: always

networks:
  pdm-game-mvp:
