DEFAULT_SESSION_ID = 'test'
GAME_TICK_INTERVAL = 0.5
TIMESTEPS_PER_MOVE = 8  # we conceptualize every player move as a full working day, or "8 hours"
TEMPERATURE_STARTING_POINT = 20
OIL_AGE_MAPPING_MAX = 365
TEMPERATURE_MAPPING_MAX = 200
MECHANICAL_WEAR_MAPPING_MAX = 100
